version: '3'

services:
  secondary_first_node:
    image: secondary_firts
    build: .
    ports:
      - 5001:5001
    restart: always
    command: bash -c "python manage.py --host=0.0.0.0 --port 5001"

  secondary_second_node:
    image: secondary_second
    build: .
    ports:
      - 5002:5002
    restart: always
    command: bash -c "python manage.py --host 0.0.0.0 --port 5002"
